services:
  trendpublish:
    image: ghcr.io/liyown/ai-trend-publish:latest
    container_name: trendpublish
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./data:/app/data
